//! Per-app classifier overrides — Phase E (#112).
//!
//! The [`crate::meeting::AppClassifier`] ships with a hard-coded
//! table of well-known meeting / media apps (Zoom, Teams, Spotify,
//! …). Real usage surfaces apps that aren't in the table and
//! occasionally classifies an app the user disagrees with — e.g. an
//! internal-tool web app the user wants treated as a meeting app, or
//! a media app they want ignored.
//!
//! This module persists user-supplied overrides keyed by app name.
//! The classifier reads them at construction (`with_overrides`) and
//! consults them before falling back to the static defaults.
//!
//! ## Schema
//!
//! See `migrations/0003_meeting_app_overrides.sql`. The table uses
//! `app_name` as the primary key — there is no auto-increment id
//! because the natural identity of an override is "which app does
//! this apply to?", and a duplicate (app_name, kind) pair is
//! meaningless.
//!
//! ## Why a dedicated repo instead of the generic
//! [`crate::repository::Repository`] trait
//!
//! The generic CRUD trait assumes an `i64` row id. Overrides are
//! identified by `app_name: String`, and the natural mutating verb
//! is "upsert" (set the kind for this app, replacing any previous
//! value), not "create". The shape doesn't earn the generic trait's
//! ergonomics, so this trait stays standalone — same call as
//! [`crate::settings::SettingsRepository`] (also `String`-keyed,
//! also upsert-shaped).

use std::sync::Arc;

use anyhow::{Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::db::SqliteDatabase;

use super::MeetingAppKind;

/// A persisted override row. Returned by `list` and `upsert`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MeetingAppOverride {
    /// App identifier the classifier matches against — bundle id on
    /// macOS, process / window class elsewhere.
    pub app_name: String,
    /// User-chosen kind. The classifier returns this verbatim
    /// instead of consulting the default table when an override
    /// exists.
    pub kind: MeetingAppKind,
    /// ISO-8601 UTC. Generated by SQLite's `strftime` default.
    /// Surfaced in the panel so the user can identify a stale row.
    pub created_at: String,
    /// Audio source the user pinned to this app (#427 Item 5
    /// foundation slice). `None` means "use the global default".
    /// When populated, a future foreground-watcher iteration will
    /// switch the active source to this value as soon as the app
    /// focuses. Storage shape mirrors `AudioSource::id()`'s
    /// surface — `"system"` for system audio, otherwise the mic
    /// device name. Read-only at the IPC boundary in this slice;
    /// upserts continue to write NULL until the panel UI lands.
    #[serde(default)]
    pub preferred_audio_source: Option<String>,
    /// Whisper model the user pinned to this app (#427 Item 5
    /// foundation slice). `None` means "use the global default".
    /// Storage shape is the catalog id string (`"whisper-base"`,
    /// etc.). Read-only at the IPC boundary in this slice;
    /// upserts continue to write NULL until the panel UI lands.
    #[serde(default)]
    pub preferred_model_id: Option<String>,
}

/// Insert / update payload. `created_at` is database-generated, so
/// callers don't supply it.
#[derive(Debug, Clone)]
pub struct NewMeetingAppOverride {
    pub app_name: String,
    pub kind: MeetingAppKind,
}

/// Storage-boundary trait. `Send + Sync` so the IPC layer can hold
/// an `Arc<dyn …>` across async commands.
#[async_trait]
pub trait MeetingAppOverrideRepository: Send + Sync {
    /// All overrides, ordered by `app_name` for deterministic
    /// rendering in the panel.
    async fn list(&self) -> Result<Vec<MeetingAppOverride>>;

    /// Insert or update the override for `app_name`. Returns the
    /// resulting row (with `created_at` populated by the database).
    /// Idempotent: calling twice with the same payload yields the
    /// same row contents.
    async fn upsert(&self, new: NewMeetingAppOverride) -> Result<MeetingAppOverride>;

    /// Delete the override for the given app. No-op if no row
    /// exists — the panel's delete button is fire-and-forget.
    /// Set or clear the per-app audio profile fields (#427 Item 5).
    /// `None` for either argument writes NULL to that column,
    /// resetting the field to "use the global default". Both args
    /// are written every call — no merge — so callers send the
    /// full intended state. Errors if the row doesn't exist; the
    /// panel UI calls `upsert` first to materialise the row.
    async fn set_profile(
        &self,
        app_name: &str,
        preferred_audio_source: Option<&str>,
        preferred_model_id: Option<&str>,
    ) -> Result<MeetingAppOverride>;

    async fn delete(&self, app_name: &str) -> Result<()>;
}

pub struct SqliteMeetingAppOverrideRepository {
    db: Arc<SqliteDatabase>,
}

impl SqliteMeetingAppOverrideRepository {
    pub fn new(db: Arc<SqliteDatabase>) -> Self {
        Self { db }
    }
}

#[async_trait]
impl MeetingAppOverrideRepository for SqliteMeetingAppOverrideRepository {
    async fn list(&self) -> Result<Vec<MeetingAppOverride>> {
        let rows = sqlx::query_as::<_, OverrideRow>(
            "SELECT app_name, kind, created_at, \
                    preferred_audio_source, preferred_model_id \
             FROM meeting_app_overrides \
             ORDER BY app_name ASC",
        )
        .fetch_all(self.db.pool())
        .await
        .context("meeting_app_overrides list")?;
        rows.into_iter().map(|r| r.try_into()).collect()
    }

    async fn upsert(&self, new: NewMeetingAppOverride) -> Result<MeetingAppOverride> {
        // SQLite's `INSERT … ON CONFLICT DO UPDATE` resets `created_at`
        // on conflict so the panel's "added at" affordance reflects
        // the most recent edit. The default expression on the column
        // re-fires on the explicit assignment.
        //
        // `preferred_audio_source` / `preferred_model_id` are not
        // touched by upsert in this foundation slice — the panel UI
        // that exposes them ships in a follow-up. On conflict the
        // existing values stay; on insert they default to NULL via
        // the migration's nullable column definition.
        let row = sqlx::query_as::<_, OverrideRow>(
            "INSERT INTO meeting_app_overrides (app_name, kind) \
             VALUES (?1, ?2) \
             ON CONFLICT(app_name) DO UPDATE SET \
                 kind = excluded.kind, \
                 created_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') \
             RETURNING app_name, kind, created_at, \
                       preferred_audio_source, preferred_model_id",
        )
        .bind(&new.app_name)
        .bind(kind_to_str(new.kind))
        .fetch_one(self.db.pool())
        .await
        .context("meeting_app_overrides upsert")?;
        row.try_into()
    }

    async fn set_profile(
        &self,
        app_name: &str,
        preferred_audio_source: Option<&str>,
        preferred_model_id: Option<&str>,
    ) -> Result<MeetingAppOverride> {
        // UPDATE-only — distinct from upsert because the panel UI
        // calls this on a row the user has already added (so the
        // row exists). Both columns are written every call so the
        // caller controls full state: pass `None` to clear, `Some`
        // to set. RETURNING surfaces the resulting row including
        // `kind` + `created_at` so the frontend can patch its
        // local list without a follow-up `list` round-trip.
        let row = sqlx::query_as::<_, OverrideRow>(
            "UPDATE meeting_app_overrides \
             SET preferred_audio_source = ?2, \
                 preferred_model_id = ?3 \
             WHERE app_name = ?1 \
             RETURNING app_name, kind, created_at, \
                       preferred_audio_source, preferred_model_id",
        )
        .bind(app_name)
        .bind(preferred_audio_source)
        .bind(preferred_model_id)
        .fetch_optional(self.db.pool())
        .await
        .context("meeting_app_overrides set_profile")?;
        match row {
            Some(r) => r.try_into(),
            None => Err(anyhow::anyhow!(
                "meeting_app_overrides set_profile: no row for app_name {app_name:?}; \
                 caller must `upsert` first"
            )),
        }
    }

    async fn delete(&self, app_name: &str) -> Result<()> {
        sqlx::query("DELETE FROM meeting_app_overrides WHERE app_name = ?1")
            .bind(app_name)
            .execute(self.db.pool())
            .await
            .context("meeting_app_overrides delete")?;
        Ok(())
    }
}

#[derive(sqlx::FromRow)]
struct OverrideRow {
    app_name: String,
    kind: String,
    created_at: String,
    preferred_audio_source: Option<String>,
    preferred_model_id: Option<String>,
}

impl TryFrom<OverrideRow> for MeetingAppOverride {
    type Error = anyhow::Error;
    fn try_from(row: OverrideRow) -> Result<Self> {
        Ok(MeetingAppOverride {
            app_name: row.app_name,
            kind: kind_from_str(&row.kind)?,
            created_at: row.created_at,
            preferred_audio_source: row.preferred_audio_source,
            preferred_model_id: row.preferred_model_id,
        })
    }
}

fn kind_to_str(kind: MeetingAppKind) -> &'static str {
    match kind {
        MeetingAppKind::Meeting => "meeting",
        MeetingAppKind::Media => "media",
        MeetingAppKind::Other => "other",
    }
}

fn kind_from_str(s: &str) -> Result<MeetingAppKind> {
    match s {
        "meeting" => Ok(MeetingAppKind::Meeting),
        "media" => Ok(MeetingAppKind::Media),
        "other" => Ok(MeetingAppKind::Other),
        _ => Err(anyhow::anyhow!("unknown meeting app kind: {s}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::SqliteDatabase;

    async fn fresh_repo() -> SqliteMeetingAppOverrideRepository {
        let db = SqliteDatabase::open_in_memory().await.unwrap();
        SqliteMeetingAppOverrideRepository::new(Arc::new(db))
    }

    #[tokio::test]
    async fn list_starts_empty() {
        let repo = fresh_repo().await;
        let rows = repo.list().await.unwrap();
        assert!(rows.is_empty());
    }

    #[tokio::test]
    async fn upsert_persists_and_returns_row() {
        let repo = fresh_repo().await;
        let row = repo
            .upsert(NewMeetingAppOverride {
                app_name: "com.example.tool".into(),
                kind: MeetingAppKind::Meeting,
            })
            .await
            .unwrap();
        assert_eq!(row.app_name, "com.example.tool");
        assert_eq!(row.kind, MeetingAppKind::Meeting);
        assert!(!row.created_at.is_empty());
    }

    #[tokio::test]
    async fn upsert_overwrites_existing_kind() {
        // Same app_name with a different kind replaces the previous
        // row — the panel's "change kind" dropdown depends on this.
        let repo = fresh_repo().await;
        repo.upsert(NewMeetingAppOverride {
            app_name: "com.example.tool".into(),
            kind: MeetingAppKind::Meeting,
        })
        .await
        .unwrap();
        let updated = repo
            .upsert(NewMeetingAppOverride {
                app_name: "com.example.tool".into(),
                kind: MeetingAppKind::Media,
            })
            .await
            .unwrap();
        assert_eq!(updated.kind, MeetingAppKind::Media);

        let all = repo.list().await.unwrap();
        assert_eq!(all.len(), 1, "upsert must not create duplicates");
        assert_eq!(all[0].kind, MeetingAppKind::Media);
    }

    #[tokio::test]
    async fn list_returns_rows_sorted_by_app_name() {
        let repo = fresh_repo().await;
        for (name, kind) in [
            ("zebra.app", MeetingAppKind::Meeting),
            ("alpha.app", MeetingAppKind::Media),
            ("middle.app", MeetingAppKind::Other),
        ] {
            repo.upsert(NewMeetingAppOverride {
                app_name: name.into(),
                kind,
            })
            .await
            .unwrap();
        }
        let rows = repo.list().await.unwrap();
        let names: Vec<_> = rows.iter().map(|r| r.app_name.as_str()).collect();
        assert_eq!(names, vec!["alpha.app", "middle.app", "zebra.app"]);
    }

    #[tokio::test]
    async fn delete_removes_row() {
        let repo = fresh_repo().await;
        repo.upsert(NewMeetingAppOverride {
            app_name: "com.example.tool".into(),
            kind: MeetingAppKind::Meeting,
        })
        .await
        .unwrap();
        repo.delete("com.example.tool").await.unwrap();
        assert!(repo.list().await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn delete_missing_row_is_noop() {
        let repo = fresh_repo().await;
        // Should not error; the panel fires this without a list
        // round-trip first.
        repo.delete("does-not-exist").await.unwrap();
    }

    #[test]
    fn kind_from_str_rejects_unknown() {
        // Defensive: if a future migration drops the CHECK
        // constraint and an unknown kind sneaks into a row, `list`
        // surfaces a clean error instead of silently coercing.
        // Direct unit-level pinning since the SQLite CHECK
        // constraint blocks the bad-row injection path at insert
        // time.
        assert!(kind_from_str("bogus").is_err());
        assert_eq!(kind_from_str("meeting").unwrap(), MeetingAppKind::Meeting);
    }

    #[tokio::test]
    async fn upsert_defaults_preferred_profile_fields_to_none() {
        // #427 Item 5 foundation slice: the new
        // `preferred_audio_source` / `preferred_model_id` columns
        // are nullable and not touched by upsert. A fresh row
        // round-trips with both fields as `None`.
        let repo = fresh_repo().await;
        let row = repo
            .upsert(NewMeetingAppOverride {
                app_name: "com.example.tool".into(),
                kind: MeetingAppKind::Meeting,
            })
            .await
            .unwrap();
        assert_eq!(row.preferred_audio_source, None);
        assert_eq!(row.preferred_model_id, None);
    }

    #[tokio::test]
    async fn upsert_preserves_existing_profile_values_on_conflict() {
        // #427 Item 5 foundation slice: when a follow-up PR plumbs
        // the panel UI it'll write `preferred_audio_source` /
        // `preferred_model_id`. The existing kind-only upsert
        // path must not stomp those values when the user later
        // changes just the classifier kind. Stamp the columns
        // directly via the pool, then re-upsert with kind only,
        // and confirm the profile values survive.
        let repo = fresh_repo().await;
        repo.upsert(NewMeetingAppOverride {
            app_name: "com.example.tool".into(),
            kind: MeetingAppKind::Meeting,
        })
        .await
        .unwrap();
        sqlx::query(
            "UPDATE meeting_app_overrides SET \
                preferred_audio_source = ?1, \
                preferred_model_id = ?2 \
             WHERE app_name = 'com.example.tool'",
        )
        .bind("system")
        .bind("whisper-base")
        .execute(repo.db.pool())
        .await
        .unwrap();

        let updated = repo
            .upsert(NewMeetingAppOverride {
                app_name: "com.example.tool".into(),
                kind: MeetingAppKind::Media,
            })
            .await
            .unwrap();
        assert_eq!(updated.kind, MeetingAppKind::Media);
        assert_eq!(updated.preferred_audio_source, Some("system".into()));
        assert_eq!(updated.preferred_model_id, Some("whisper-base".into()));
    }

    #[tokio::test]
    async fn set_profile_sets_both_fields_then_clears_them() {
        let repo = fresh_repo().await;
        repo.upsert(NewMeetingAppOverride {
            app_name: "com.example.tool".into(),
            kind: MeetingAppKind::Meeting,
        })
        .await
        .unwrap();

        // Set both fields.
        let row = repo
            .set_profile("com.example.tool", Some("system"), Some("whisper-base"))
            .await
            .unwrap();
        assert_eq!(row.preferred_audio_source, Some("system".into()));
        assert_eq!(row.preferred_model_id, Some("whisper-base".into()));

        // Clear both — None means NULL, the canonical "use the
        // global default" sentinel.
        let cleared = repo
            .set_profile("com.example.tool", None, None)
            .await
            .unwrap();
        assert_eq!(cleared.preferred_audio_source, None);
        assert_eq!(cleared.preferred_model_id, None);
    }

    #[tokio::test]
    async fn set_profile_writes_full_state_no_merge() {
        // Caller controls full state on every call: setting
        // `audio_source = Some` and `model_id = None` clears the
        // model even if it was previously set. This is the panel
        // UI's expected shape — the user toggles either dropdown
        // and the form sends the full intended state.
        let repo = fresh_repo().await;
        repo.upsert(NewMeetingAppOverride {
            app_name: "com.example.tool".into(),
            kind: MeetingAppKind::Meeting,
        })
        .await
        .unwrap();
        repo.set_profile("com.example.tool", Some("system"), Some("whisper-base"))
            .await
            .unwrap();

        // Now set audio_source only; model should be cleared.
        let row = repo
            .set_profile("com.example.tool", Some("Built-in mic"), None)
            .await
            .unwrap();
        assert_eq!(row.preferred_audio_source, Some("Built-in mic".into()));
        assert_eq!(row.preferred_model_id, None);
    }

    #[tokio::test]
    async fn set_profile_errors_when_row_missing() {
        // Panel UI is expected to upsert first; a missing row at
        // set_profile time means client + server are out of sync
        // (e.g. the user deleted the override in another tab).
        // Surface as an error so the panel can re-list.
        let repo = fresh_repo().await;
        let result = repo
            .set_profile("does-not-exist", Some("system"), None)
            .await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn list_round_trips_populated_profile_values() {
        // Direct write into the table so this test doesn't depend
        // on the future panel-UI upsert path. Confirms the SELECT
        // pulls the new columns into the deserialised struct.
        let repo = fresh_repo().await;
        sqlx::query(
            "INSERT INTO meeting_app_overrides \
                (app_name, kind, preferred_audio_source, preferred_model_id) \
             VALUES ('com.example.tool', 'meeting', 'system', 'whisper-large-v3')",
        )
        .execute(repo.db.pool())
        .await
        .unwrap();

        let rows = repo.list().await.unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].preferred_audio_source, Some("system".into()));
        assert_eq!(rows[0].preferred_model_id, Some("whisper-large-v3".into()));
    }
}
