//! Meeting Mode — passive transcription of meeting / multi-speaker
//! audio sessions.
//!
//! Concept inspired by VoiceInk's writing-mode plus typical meeting-
//! transcript tools. Reimplemented from observed public behaviour and
//! the design memo at `docs/system-audio-meeting-mode-proposal.md`;
//! no source code referenced. See §13.8 of the PRD.
//!
//! ## Module layout
//!
//! - **`mod.rs`** — shared types: `MeetingAppKind`, `MeetingSession`,
//!   `PersistedUtterance`, the `MeetingSessionRepository` trait.
//! - **`manager`** — `SessionManager` runtime: lifecycle state
//!   machine, chunking pump, `AppClassifier` for foreground-app
//!   detection. Driven manually today; auto-start on classifier
//!   verdict is the open piece of #112.
//! - **`app_overrides`** — per-app classifier override storage
//!   (#112/#192). The Settings panel reads/writes through here;
//!   `SessionManager` reads a fresh snapshot at every session
//!   start so edits take effect without a restart.
//! - **`sqlite`** — `SqliteMeetingSessionRepository` persistence.
//!
//! Streaming inference + diarization compose externally:
//! `Transcribe::start_stream` (#108) feeds the pump; `Diarize`
//! (#191/#201) labels the finals before dispatch.
//!
//! ## Privacy invariant
//!
//! Only transcripts and timestamps land here. Raw audio bytes are
//! never persisted — they live in a RAM ring buffer during
//! inference and are discarded once each window has been
//! transcribed. The trait shape enforces this by accepting
//! `Utterance`s (text + timestamps) rather than audio buffers as
//! the input shape — there's no way to insert a `Vec<f32>` through
//! the data layer's API surface.

pub mod app_overrides;
pub mod manager;
pub mod sqlite;

pub use app_overrides::{
    MeetingAppOverride, MeetingAppOverrideRepository, NewMeetingAppOverride,
    SqliteMeetingAppOverrideRepository,
};
pub use manager::{AppClassifier, MeetingEventEmitter, NoopMeetingEventEmitter, SessionManager};
pub use sqlite::SqliteMeetingSessionRepository;

use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::repository::Repository;

/// Classifier verdict at session-open time. Persisted on the row so
/// a later classifier change doesn't retroactively re-label past
/// sessions.
///
/// `serde` derives use kebab-case so the wire shape matches the
/// frontend's discriminated union types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum MeetingAppKind {
    /// A meeting platform (Zoom, Teams, Meet, Discord, Slack-call).
    /// Default behaviour: surface the "start session?" prompt.
    Meeting,
    /// A media app (YouTube, Spotify, Apple Music). Default
    /// behaviour: do not auto-record. The user can opt in per-app.
    Media,
    /// Anything else. Doesn't trigger a session unless the user
    /// manually starts one via [`#110`'s] manual-start path.
    ///
    /// [`#110`'s]: https://github.com/khawkins98/Hush/issues/110
    Other,
}

/// A persisted meeting session. Mirrors migration 0002's
/// `meeting_sessions` table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MeetingSession {
    pub id: i64,
    /// Bundle id / process name of the foreground app at session
    /// start (e.g. `"us.zoom.xos"`).
    pub app_name: String,
    pub app_kind: MeetingAppKind,
    /// ISO-8601 UTC. Generated by SQLite's `strftime` default;
    /// callers don't supply it.
    pub started_at: String,
    /// `None` while the session is in-flight; populated when the
    /// session closes.
    pub ended_at: Option<String>,
    /// Distinct speaker count for the session. Populated by the
    /// diarizer when D2 (model-based) lands; the D1 silence-gap
    /// heuristic doesn't produce a stable count, so this stays
    /// `None` for D1 sessions.
    pub speaker_count: Option<i64>,
    /// Denormalised count so the panel's session-list view doesn't
    /// need a `JOIN COUNT(*)` per row.
    pub utterance_count: i64,
    /// User-editable freeform note. The panel renders an "add notes"
    /// affordance when empty.
    pub notes: Option<String>,
}

/// Fields the caller supplies when opening a session. Separate from
/// [`MeetingSession`] so database-generated fields (id, started_at)
/// can't be hand-rolled.
#[derive(Debug, Clone)]
pub struct NewMeetingSession {
    pub app_name: String,
    pub app_kind: MeetingAppKind,
}

/// Persisted utterance row. Mirrors migration 0002's `utterances`
/// table.
///
/// **Distinct from [`crate::transcription::Utterance`]**: the
/// transcription-layer `Utterance` is the wire shape the streaming
/// backend emits; this is the persisted row with a foreign key to
/// the parent session and an integer id. The session manager (#110)
/// converts between them when it inserts a final utterance.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistedUtterance {
    pub id: i64,
    pub session_id: i64,
    pub started_at_ms: i64,
    pub ended_at_ms: i64,
    /// Set by the diarizer (D1 `EnergyDiarizer` ships "Speaker A" /
    /// "Speaker B"; #201). Falls back to the source-derived
    /// `"mic"` / `"system"` tag when the diarizer abstains.
    pub speaker_label: Option<String>,
    pub text: String,
    /// Reserved. v1 only persists `is_final = true` utterances; the
    /// column exists so a future "show recent partials in the
    /// timeline" feature can persist them without a migration.
    pub is_final: bool,
}

/// Fields a caller supplies when persisting a final utterance.
#[derive(Debug, Clone)]
pub struct NewPersistedUtterance {
    pub session_id: i64,
    pub started_at_ms: i64,
    pub ended_at_ms: i64,
    pub speaker_label: Option<String>,
    pub text: String,
}

/// Storage-boundary trait for meeting sessions.
///
/// Extends the generic [`Repository<MeetingSession, NewMeetingSession, i64>`]
/// with the session-specific methods that don't fit the generic CRUD
/// shape — closing a session, appending an utterance to it,
/// listing the utterances, editing the notes.
///
/// **Why a single trait, not the marker + extension pattern this code
/// previously used.** Round-7 architecture review (closes #115) flagged
/// the two-trait setup as the wrong shape:
///
/// - The dictionary repos ([`crate::dictionary::ReplacementRepository`]
///   / [`crate::dictionary::VocabularyRepository`]) are *pure* markers
///   plus a blanket impl over `Repository<T, NewT, Id>` because they
///   have no domain-specific methods. The marker pattern earns its
///   keep there.
/// - Meeting was the first repo with session-specific logic. The
///   earlier code chose a new pattern (marker + extension trait +
///   blanket impl forwarding through the extension) rather than just
///   declaring the methods on the supertrait directly.
/// - The forwarding boilerplate, the doubled mock surface (every test
///   mock had to impl two traits), and the cognitive load at every
///   call site outweighed the marker-pattern benefit. Concrete
///   impls now implement `Repository<...>` AND
///   `MeetingSessionRepository` — same shape every other domain repo
///   with extra methods would naturally take.
///
/// `Send + Sync` so the IPC layer can hold an
/// `Arc<dyn MeetingSessionRepository>` across async Tauri commands.
#[async_trait]
pub trait MeetingSessionRepository:
    Repository<MeetingSession, NewMeetingSession, i64> + Send + Sync
{
    /// Mark a session closed: writes `ended_at = now`. No-op if the
    /// session is already closed.
    async fn close_session(&self, id: i64) -> Result<()>;

    /// Persist a final utterance against an open session. Bumps the
    /// session's `utterance_count` atomically (in a single transaction)
    /// so the denormalised count never drifts from the actual row count.
    async fn append_utterance(&self, new: NewPersistedUtterance) -> Result<PersistedUtterance>;

    /// All utterances for a session, oldest-first. Used by the
    /// session-detail view to render the transcript.
    async fn list_utterances(&self, session_id: i64) -> Result<Vec<PersistedUtterance>>;

    /// Update a session's freeform notes. The panel calls this on
    /// blur of the notes textarea.
    async fn set_notes(&self, id: i64, notes: Option<String>) -> Result<()>;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Compile-time check that the trait is object-safe — without
    /// this, the IPC layer can't hold an
    /// `Arc<dyn MeetingSessionRepository>`.
    #[test]
    fn meeting_session_repository_is_object_safe() {
        fn _assert_object_safe(_: &dyn MeetingSessionRepository) {}
    }

    #[test]
    fn meeting_app_kind_serde_uses_kebab_case() {
        // The frontend's discriminated-union TypeScript type matches
        // on these strings. Pin so a Rust-side rename fails loud here
        // rather than silently producing untranslatable wire shapes.
        assert_eq!(
            serde_json::to_string(&MeetingAppKind::Meeting).unwrap(),
            r#""meeting""#
        );
        assert_eq!(
            serde_json::to_string(&MeetingAppKind::Media).unwrap(),
            r#""media""#
        );
        assert_eq!(
            serde_json::to_string(&MeetingAppKind::Other).unwrap(),
            r#""other""#
        );
    }

    #[test]
    fn meeting_session_serde_uses_camel_case() {
        // Same wire-shape discipline as the other persisted shapes.
        // The frontend's MeetingSessionsPanel reads `appName`,
        // `appKind`, `startedAt`, etc.
        let s = MeetingSession {
            id: 1,
            app_name: "us.zoom.xos".into(),
            app_kind: MeetingAppKind::Meeting,
            started_at: "2026-04-26T15:00:00Z".into(),
            ended_at: None,
            speaker_count: None,
            utterance_count: 0,
            notes: None,
        };
        let json = serde_json::to_string(&s).unwrap();
        assert!(json.contains(r#""appName":"us.zoom.xos""#), "got: {json}");
        assert!(json.contains(r#""appKind":"meeting""#), "got: {json}");
        assert!(
            json.contains(r#""startedAt":"2026-04-26T15:00:00Z""#),
            "got: {json}"
        );
        assert!(json.contains(r#""utteranceCount":0"#), "got: {json}");
    }
}
