//! SQLite-backed implementation of the meeting-mode data layer.
//!
//! Mirrors the shape of [`crate::history::SqliteHistoryRepository`]
//! and the dictionary repos: every method is a single round-trip
//! query (or a small transaction for `append_utterance`'s
//! count-bump). FTS5 search over `utterances.text` flows through
//! the trigger-maintained `utterances_fts` virtual table from
//! migration 0002.

use std::sync::Arc;

use anyhow::{Context, Result};
use async_trait::async_trait;

use crate::db::SqliteDatabase;
use crate::repository::Repository;

use super::{
    MeetingAppKind, MeetingSession, MeetingSessionRepository, NewMeetingSession,
    NewPersistedUtterance, PersistedUtterance,
};

/// Concrete repository backed by a [`SqliteDatabase`] pool.
pub struct SqliteMeetingSessionRepository {
    db: Arc<SqliteDatabase>,
}

impl SqliteMeetingSessionRepository {
    pub fn new(db: Arc<SqliteDatabase>) -> Self {
        Self { db }
    }
}

#[async_trait]
impl Repository<MeetingSession, NewMeetingSession, i64> for SqliteMeetingSessionRepository {
    async fn list(&self) -> Result<Vec<MeetingSession>> {
        // Newest-first matches the panel's "your recent sessions"
        // affordance — the user is most likely to want what they
        // just finished, not the meeting they had three weeks ago.
        sqlx::query_as::<_, MeetingSession>(
            "SELECT id, app_name, app_kind, started_at, ended_at, \
                    speaker_count, utterance_count, notes, sources, app_title, name \
             FROM meeting_sessions \
             ORDER BY started_at DESC, id DESC",
        )
        .fetch_all(self.db.pool())
        .await
        .context("list meeting sessions")
    }

    async fn create(&self, new: NewMeetingSession) -> Result<MeetingSession> {
        // `started_at` is generated by SQLite's strftime default.
        // RETURNING gives us the row in one round-trip.
        let kind_str = app_kind_to_str(new.app_kind);
        // Sources persisted as comma-separated kind labels (#242).
        // Empty Vec → NULL so the legacy-row case (no sources
        // recorded) and the explicit-empty case stay
        // indistinguishable; the panel falls back to "no source
        // info" for both, which is what we want.
        let sources_csv: Option<String> = if new.sources.is_empty() {
            None
        } else {
            Some(new.sources.join(","))
        };
        let row: MeetingSession = sqlx::query_as(
            "INSERT INTO meeting_sessions (app_name, app_kind, sources, app_title) \
             VALUES (?, ?, ?, ?) \
             RETURNING id, app_name, app_kind, started_at, ended_at, \
                       speaker_count, utterance_count, notes, sources, app_title, name",
        )
        .bind(&new.app_name)
        .bind(kind_str)
        .bind(sources_csv)
        .bind(&new.app_title)
        .fetch_one(self.db.pool())
        .await
        .context("insert meeting session")?;
        Ok(row)
    }

    async fn update(&self, item: MeetingSession) -> Result<()> {
        // Only the fields the user can actually change post-creation:
        // `notes`, `speaker_count`, `utterance_count`, `ended_at`.
        // Identity fields (id, app_name, app_kind, started_at) are
        // immutable from the user's perspective.
        let kind_str = app_kind_to_str(item.app_kind);
        sqlx::query(
            "UPDATE meeting_sessions \
             SET app_kind = ?, ended_at = ?, speaker_count = ?, utterance_count = ?, notes = ? \
             WHERE id = ?",
        )
        .bind(kind_str)
        .bind(&item.ended_at)
        .bind(item.speaker_count)
        .bind(item.utterance_count)
        .bind(&item.notes)
        .bind(item.id)
        .execute(self.db.pool())
        .await
        .context("update meeting session")?;
        Ok(())
    }

    async fn delete(&self, id: i64) -> Result<()> {
        // Cascade is configured on the FK from utterances back to
        // meeting_sessions, so deleting the session row also
        // deletes its utterances. Same no-op-on-missing semantics
        // as the rest of the repos.
        sqlx::query("DELETE FROM meeting_sessions WHERE id = ?")
            .bind(id)
            .execute(self.db.pool())
            .await
            .context("delete meeting session")?;
        Ok(())
    }
}

#[async_trait]
impl MeetingSessionRepository for SqliteMeetingSessionRepository {
    async fn close_session(&self, id: i64) -> Result<()> {
        // Sets `ended_at = now`. No-op if the row is already closed
        // (the COALESCE guards against double-write so a second close
        // doesn't drift the timestamp later than the first.)
        let result = sqlx::query(
            "UPDATE meeting_sessions \
             SET ended_at = COALESCE(ended_at, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')) \
             WHERE id = ?",
        )
        .bind(id)
        .execute(self.db.pool())
        .await
        .context("close meeting session")?;
        if result.rows_affected() == 0 {
            anyhow::bail!("meeting session {id} not found");
        }
        Ok(())
    }

    async fn append_utterance(
        &self,
        new: NewPersistedUtterance,
    ) -> Result<Option<PersistedUtterance>> {
        // Two-step transaction: insert the utterance, bump the
        // session's denormalised count. Atomic so the count never
        // drifts past a concurrent insert. is_final=1 forced — the
        // schema column exists for a future "persist partials"
        // feature but v1 only writes finals.
        //
        // The INSERT uses a conditional SELECT form so it only fires
        // if the session is still open (ended_at IS NULL). This closes
        // the race between stop_manual and append_if_active (#917):
        // if stop_manual won the race, fetch_optional returns None and
        // we skip the count bump, leaving the closed session clean.
        let mut tx = self
            .db
            .pool()
            .begin()
            .await
            .context("begin append_utterance tx")?;

        let utterance: Option<PersistedUtterance> = sqlx::query_as(
            "INSERT INTO utterances (session_id, started_at_ms, ended_at_ms, speaker_label, text, is_final) \
             SELECT ?, ?, ?, ?, ?, 1 \
             WHERE EXISTS (SELECT 1 FROM meeting_sessions WHERE id = ? AND ended_at IS NULL) \
             RETURNING id, session_id, started_at_ms, ended_at_ms, speaker_label, text, is_final",
        )
        .bind(new.session_id)
        .bind(new.started_at_ms)
        .bind(new.ended_at_ms)
        .bind(&new.speaker_label)
        .bind(&new.text)
        .bind(new.session_id)
        .fetch_optional(&mut *tx)
        .await
        .context("insert utterance")?;

        if utterance.is_some() {
            sqlx::query(
                "UPDATE meeting_sessions \
                 SET utterance_count = utterance_count + 1 \
                 WHERE id = ?",
            )
            .bind(new.session_id)
            .execute(&mut *tx)
            .await
            .context("bump session utterance_count")?;
        }

        tx.commit().await.context("commit append_utterance tx")?;
        Ok(utterance)
    }

    async fn list_utterances(&self, session_id: i64) -> Result<Vec<PersistedUtterance>> {
        sqlx::query_as::<_, PersistedUtterance>(
            "SELECT id, session_id, started_at_ms, ended_at_ms, speaker_label, text, is_final \
             FROM utterances \
             WHERE session_id = ? \
             ORDER BY started_at_ms ASC",
        )
        .bind(session_id)
        .fetch_all(self.db.pool())
        .await
        .context("list utterances")
    }

    async fn set_notes(&self, id: i64, notes: Option<String>) -> Result<()> {
        let result = sqlx::query("UPDATE meeting_sessions SET notes = ? WHERE id = ?")
            .bind(&notes)
            .bind(id)
            .execute(self.db.pool())
            .await
            .context("set meeting session notes")?;
        if result.rows_affected() == 0 {
            anyhow::bail!("meeting session {id} not found");
        }
        Ok(())
    }

    async fn set_name(&self, id: i64, name: Option<String>) -> Result<()> {
        let name = name.and_then(|n| {
            let t = n.trim().to_owned();
            if t.is_empty() { None } else { Some(t) }
        });
        let result = sqlx::query("UPDATE meeting_sessions SET name = ? WHERE id = ?")
            .bind(&name)
            .bind(id)
            .execute(self.db.pool())
            .await
            .context("set meeting session name")?;
        if result.rows_affected() == 0 {
            anyhow::bail!("meeting session {id} not found");
        }
        Ok(())
    }

    async fn get_by_id(&self, id: i64) -> Result<Option<MeetingSession>> {
        // Single B-tree probe via the PK index. Mirrors the
        // column list in `list()` so a future column add (e.g.
        // migration 0006) only needs to touch one place — both
        // queries fail loud at compile time if they drift.
        sqlx::query_as::<_, MeetingSession>(
            "SELECT id, app_name, app_kind, started_at, ended_at, \
                    speaker_count, utterance_count, notes, sources, app_title, name \
             FROM meeting_sessions \
             WHERE id = ?",
        )
        .bind(id)
        .fetch_optional(self.db.pool())
        .await
        .context("get meeting session by id")
    }

    async fn list_open_sessions(&self) -> Result<Vec<MeetingSession>> {
        // Sessions left open from a crashed / killed previous
        // run (#249). The `ended_at IS NULL` predicate mirrors
        // the shape `close_session`'s COALESCE guard checks, so
        // the two paths stay consistent: a row that's already
        // closed won't reappear here, and reconciliation only
        // touches genuinely-orphaned rows.
        sqlx::query_as::<_, MeetingSession>(
            "SELECT id, app_name, app_kind, started_at, ended_at, \
                    speaker_count, utterance_count, notes, sources, app_title, name \
             FROM meeting_sessions \
             WHERE ended_at IS NULL \
             ORDER BY started_at DESC, id DESC",
        )
        .fetch_all(self.db.pool())
        .await
        .context("list open meeting sessions")
    }

    async fn search_sessions(&self, query: &str) -> Result<Vec<MeetingSession>> {
        // Cross-stream search (#357 phase 2): roll up FTS5 hits on
        // utterance text to one row per session. The phrase wrap
        // matches the dictation `history_search` shape — quote the
        // user's input so FTS5 treats it as a literal phrase
        // rather than parsing operators (`OR`, `NOT`, …) the UI
        // doesn't currently expose. Escapes embedded double quotes
        // by doubling them, same as SQLite's identifier quoting.
        let phrase = format!("\"{}\"", query.replace('"', "\"\""));

        sqlx::query_as::<_, MeetingSession>(
            "SELECT s.id, s.app_name, s.app_kind, s.started_at, s.ended_at, \
                    s.speaker_count, s.utterance_count, s.notes, s.sources, s.app_title, s.name \
             FROM meeting_sessions s \
             WHERE s.id IN ( \
                SELECT DISTINCT u.session_id \
                FROM utterances u \
                INNER JOIN utterances_fts fts ON fts.rowid = u.id \
                WHERE utterances_fts MATCH ? \
             ) \
             ORDER BY s.started_at DESC, s.id DESC",
        )
        .bind(phrase)
        .fetch_all(self.db.pool())
        .await
        .context("search meeting sessions")
    }
}

/// String form for the `app_kind` column. Kept in one place so the
/// SELECT and INSERT paths can't drift.
fn app_kind_to_str(kind: MeetingAppKind) -> &'static str {
    match kind {
        MeetingAppKind::Meeting => "meeting",
        MeetingAppKind::Media => "media",
        MeetingAppKind::Other => "other",
    }
}

fn app_kind_from_str(s: &str) -> std::result::Result<MeetingAppKind, sqlx::Error> {
    // Fail loud on unrecognised values rather than silently defaulting
    // to `Other`. The earlier silent-default approach masked data
    // corruption (a rogue write of `"video-call"` would render in the
    // panel as a nondescript "Other" session, with no signal that
    // anything was wrong). Round-7 technical-quality reviewer caught
    // it. A future variant added to the enum is a deliberate code
    // change that updates this match arm; the database is never
    // expected to hold values this match doesn't cover.
    match s {
        "meeting" => Ok(MeetingAppKind::Meeting),
        "media" => Ok(MeetingAppKind::Media),
        "other" => Ok(MeetingAppKind::Other),
        unknown => Err(sqlx::Error::Decode(
            format!(
                "unknown meeting_sessions.app_kind value: {unknown:?} \
                 (expected one of: meeting, media, other)"
            )
            .into(),
        )),
    }
}

// Hand-rolled `FromRow` impls. Keeping parity with the history /
// dictionary repos: derive-`FromRow` would require enabling sqlx's
// derive feature for the whole crate, which we've avoided so far.

impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for MeetingSession {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> std::result::Result<Self, sqlx::Error> {
        use sqlx::Row;
        let kind_str: String = row.try_get("app_kind")?;
        // CSV → Vec<String>, NULL → None (legacy rows and
        // explicit-empty inserts; see `create` above).
        let sources_csv: Option<String> = row.try_get("sources")?;
        let sources = sources_csv.map(|s| {
            s.split(',')
                .map(|p| p.trim().to_owned())
                .filter(|p| !p.is_empty())
                .collect::<Vec<_>>()
        });
        Ok(MeetingSession {
            id: row.try_get("id")?,
            app_name: row.try_get("app_name")?,
            app_kind: app_kind_from_str(&kind_str)?,
            started_at: row.try_get("started_at")?,
            ended_at: row.try_get("ended_at")?,
            speaker_count: row.try_get("speaker_count")?,
            utterance_count: row.try_get("utterance_count")?,
            notes: row.try_get("notes")?,
            sources,
            app_title: row.try_get("app_title")?,
            name: row.try_get("name")?,
        })
    }
}

impl<'r> sqlx::FromRow<'r, sqlx::sqlite::SqliteRow> for PersistedUtterance {
    fn from_row(row: &'r sqlx::sqlite::SqliteRow) -> std::result::Result<Self, sqlx::Error> {
        use sqlx::Row;
        let is_final_int: i64 = row.try_get("is_final")?;
        Ok(PersistedUtterance {
            id: row.try_get("id")?,
            session_id: row.try_get("session_id")?,
            started_at_ms: row.try_get("started_at_ms")?,
            ended_at_ms: row.try_get("ended_at_ms")?,
            speaker_label: row.try_get("speaker_label")?,
            text: row.try_get("text")?,
            is_final: is_final_int != 0,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn fresh_repo() -> SqliteMeetingSessionRepository {
        let db = SqliteDatabase::open_in_memory()
            .await
            .expect("in-memory db");
        SqliteMeetingSessionRepository::new(Arc::new(db))
    }

    fn sample_new() -> NewMeetingSession {
        NewMeetingSession {
            app_name: "us.zoom.xos".into(),
            app_kind: MeetingAppKind::Meeting,
            sources: vec!["mic".into(), "system".into()],
            app_title: Some("Q3 Standup".into()),
        }
    }

    #[tokio::test]
    async fn create_then_list_returns_the_session() {
        let repo = fresh_repo().await;
        let created = repo.create(sample_new()).await.unwrap();
        assert!(created.id > 0);
        assert_eq!(created.app_name, "us.zoom.xos");
        assert_eq!(created.app_kind, MeetingAppKind::Meeting);
        assert_eq!(created.utterance_count, 0);
        assert!(created.ended_at.is_none(), "new session is open");
        assert_eq!(
            created.sources,
            Some(vec!["mic".to_owned(), "system".to_owned()]),
            "sources column round-trips populated input"
        );
        assert_eq!(
            created.app_title,
            Some("Q3 Standup".to_owned()),
            "app_title column round-trips populated input"
        );

        let all = repo.list().await.unwrap();
        assert_eq!(all.len(), 1);
        assert_eq!(all[0], created);
    }

    /// Legacy-row compatibility for migration 0004 (#244).
    /// Rows created before the `sources` column existed have NULL
    /// stored, which the FromRow impl maps to `Option::None`. The
    /// `create()` path always supplies sources today, so the only
    /// way to reach this state in production is a database that
    /// pre-dates the migration. We simulate that by inserting via
    /// raw SQL that omits the new column.
    #[tokio::test]
    async fn legacy_row_with_null_sources_round_trips_as_none() {
        let repo = fresh_repo().await;

        sqlx::query("INSERT INTO meeting_sessions (app_name, app_kind) VALUES (?, ?)")
            .bind("legacy.app")
            .bind("meeting")
            .execute(repo.db.pool())
            .await
            .expect("legacy insert");

        let all = repo.list().await.unwrap();
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].app_name, "legacy.app");
        assert!(
            all[0].sources.is_none(),
            "NULL sources column maps to None, not Some(vec![])"
        );
        assert!(
            all[0].app_title.is_none(),
            "NULL app_title column maps to None"
        );
    }

    #[tokio::test]
    async fn close_session_writes_ended_at_and_is_idempotent() {
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();

        repo.close_session(s.id).await.unwrap();
        let after_first = repo.list().await.unwrap()[0].clone();
        assert!(
            after_first.ended_at.is_some(),
            "first close stamps ended_at"
        );

        // Idempotent: a second close doesn't drift the timestamp
        // forward. Pinned because if a future refactor "fixed" the
        // COALESCE guard it'd silently make every re-close move
        // the timestamp later, which would mis-report durations
        // for sessions that get re-touched (e.g. after a restart).
        repo.close_session(s.id).await.unwrap();
        let after_second = repo.list().await.unwrap()[0].clone();
        assert_eq!(after_second.ended_at, after_first.ended_at);
    }

    #[tokio::test]
    async fn list_open_sessions_returns_only_unclosed_rows() {
        // Orphan-reconciliation primitive (#249). The query
        // filters `ended_at IS NULL`; a row that's been closed
        // must not appear, and a freshly-created row must.
        let repo = fresh_repo().await;
        let open = repo.create(sample_new()).await.unwrap();
        let closed = repo.create(sample_new()).await.unwrap();
        repo.close_session(closed.id).await.unwrap();

        let still_open = repo.list_open_sessions().await.unwrap();
        assert_eq!(still_open.len(), 1, "only the unclosed row is open");
        assert_eq!(still_open[0].id, open.id);

        // After closing the remaining row, the list is empty.
        repo.close_session(open.id).await.unwrap();
        assert!(repo.list_open_sessions().await.unwrap().is_empty());
    }

    #[tokio::test]
    async fn append_utterance_inserts_and_bumps_count() {
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();

        let u = repo
            .append_utterance(NewPersistedUtterance {
                session_id: s.id,
                started_at_ms: 1_000,
                ended_at_ms: 4_500,
                speaker_label: None,
                text: "hello world".into(),
            })
            .await
            .unwrap()
            .expect("session open — utterance should be inserted");
        assert!(u.id > 0);
        assert_eq!(u.session_id, s.id);
        assert!(u.is_final);
        assert!(u.speaker_label.is_none(), "no label was supplied on insert");

        // Count was bumped atomically.
        let after = repo.list().await.unwrap()[0].clone();
        assert_eq!(after.utterance_count, 1);

        // Second append → count 2.
        repo.append_utterance(NewPersistedUtterance {
            session_id: s.id,
            started_at_ms: 5_000,
            ended_at_ms: 6_000,
            speaker_label: None,
            text: "still here".into(),
        })
        .await
        .unwrap();
        let after_second = repo.list().await.unwrap()[0].clone();
        assert_eq!(after_second.utterance_count, 2);
    }

    #[tokio::test]
    async fn list_utterances_returns_session_rows_in_time_order() {
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();

        repo.append_utterance(NewPersistedUtterance {
            session_id: s.id,
            started_at_ms: 5_000,
            ended_at_ms: 6_000,
            speaker_label: None,
            text: "second".into(),
        })
        .await
        .unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: s.id,
            started_at_ms: 1_000,
            ended_at_ms: 2_000,
            speaker_label: None,
            text: "first".into(),
        })
        .await
        .unwrap();

        let utterances = repo.list_utterances(s.id).await.unwrap();
        assert_eq!(utterances.len(), 2);
        assert_eq!(utterances[0].text, "first", "ordered by started_at_ms ASC");
        assert_eq!(utterances[1].text, "second");
    }

    #[tokio::test]
    async fn set_notes_round_trips() {
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();

        repo.set_notes(s.id, Some("Action: follow up with K".into()))
            .await
            .unwrap();
        let after = repo.list().await.unwrap()[0].clone();
        assert_eq!(after.notes.as_deref(), Some("Action: follow up with K"));

        // Clearing notes works.
        repo.set_notes(s.id, None).await.unwrap();
        let after_clear = repo.list().await.unwrap()[0].clone();
        assert!(after_clear.notes.is_none());
    }

    #[tokio::test]
    async fn search_sessions_matches_any_utterance_hit() {
        // #357 phase 2: a session is in the search result if any of
        // its utterances match the query. The test seeds two
        // sessions, gives each a distinguishing utterance, and
        // confirms the right session(s) come back for a per-keyword
        // probe and for a cross-cutting keyword.
        let repo = fresh_repo().await;

        let alpha = repo
            .create(NewMeetingSession {
                app_name: "Alpha".to_string(),
                app_kind: MeetingAppKind::Meeting,
                sources: vec!["mic".into()],
                app_title: None,
            })
            .await
            .unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: alpha.id,
            started_at_ms: 0,
            ended_at_ms: 1_000,
            speaker_label: None,
            text: "kubernetes deployment failed".into(),
        })
        .await
        .unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: alpha.id,
            started_at_ms: 1_000,
            ended_at_ms: 2_000,
            speaker_label: None,
            text: "shared everywhere".into(),
        })
        .await
        .unwrap();

        let beta = repo
            .create(NewMeetingSession {
                app_name: "Beta".to_string(),
                app_kind: MeetingAppKind::Meeting,
                sources: vec!["mic".into()],
                app_title: None,
            })
            .await
            .unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: beta.id,
            started_at_ms: 0,
            ended_at_ms: 1_000,
            speaker_label: None,
            text: "shared everywhere".into(),
        })
        .await
        .unwrap();

        // Per-session keyword: only alpha matches.
        let kube_hits = repo.search_sessions("kubernetes").await.unwrap();
        let kube_ids: Vec<i64> = kube_hits.iter().map(|s| s.id).collect();
        assert_eq!(kube_ids, vec![alpha.id]);

        // Cross-session keyword: both sessions match. We don't pin
        // the order here because SQLite's default `started_at` has
        // single-second resolution and the two creates happen
        // back-to-back; the ORDER BY is verified by the
        // `list_sessions_returns_*` tests that seed wider gaps.
        let shared_hits = repo.search_sessions("shared").await.unwrap();
        let mut shared_ids: Vec<i64> = shared_hits.iter().map(|s| s.id).collect();
        shared_ids.sort();
        let mut expected = vec![alpha.id, beta.id];
        expected.sort();
        assert_eq!(shared_ids, expected);

        // No-match query: empty result.
        let miss = repo
            .search_sessions("definitely-nothing-here")
            .await
            .unwrap();
        assert!(miss.is_empty());
    }

    #[tokio::test]
    async fn search_sessions_returns_each_session_once_even_when_many_utterances_match() {
        // Audit-of-audit hazard from the dictation-FTS shape: a
        // naive INNER JOIN against the FTS table would yield one
        // row per matching utterance, so a session with N matching
        // utterances would appear N times. The repo uses
        // `WHERE id IN (SELECT DISTINCT session_id ...)` to roll
        // up — pin that here so a future refactor doesn't regress.
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();
        for i in 0..5 {
            repo.append_utterance(NewPersistedUtterance {
                session_id: s.id,
                started_at_ms: i * 1_000,
                ended_at_ms: (i + 1) * 1_000,
                speaker_label: None,
                text: format!("repeated keyword {i}"),
            })
            .await
            .unwrap();
        }

        let hits = repo.search_sessions("repeated").await.unwrap();
        assert_eq!(
            hits.len(),
            1,
            "session deduplicated despite 5 matching utterances"
        );
        assert_eq!(hits[0].id, s.id);
    }

    #[tokio::test]
    async fn search_sessions_quotes_user_query_so_operators_are_literal() {
        // FTS5 parses bare `OR` / `NOT` as operators. The repo wraps
        // the user input in double quotes so it's treated as a
        // literal phrase — same shape `history_search` uses. The
        // probe here uses a phrase containing what would otherwise
        // be an operator and confirms the behaviour is "find this
        // exact text" not "match either token".
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: s.id,
            started_at_ms: 0,
            ended_at_ms: 1_000,
            speaker_label: None,
            text: "either OR neither here".into(),
        })
        .await
        .unwrap();

        let hits = repo.search_sessions("OR").await.unwrap();
        assert_eq!(
            hits.len(),
            1,
            "OR is treated as a literal token, not an operator",
        );
    }

    #[tokio::test]
    async fn delete_cascades_to_utterances() {
        // Belt-and-braces: confirms migration 0002's ON DELETE
        // CASCADE actually fires. If it didn't, deleting a session
        // would leave orphan utterance rows in place, which the
        // panel would then render as belonging to a vanished session.
        let repo = fresh_repo().await;
        let s = repo.create(sample_new()).await.unwrap();
        repo.append_utterance(NewPersistedUtterance {
            session_id: s.id,
            started_at_ms: 0,
            ended_at_ms: 1_000,
            speaker_label: None,
            text: "ghost".into(),
        })
        .await
        .unwrap();

        repo.delete(s.id).await.unwrap();
        assert!(repo.list().await.unwrap().is_empty());
        assert!(
            repo.list_utterances(s.id).await.unwrap().is_empty(),
            "utterances should cascade-delete with their session"
        );
    }
}
